/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated/app/index'
import { Route as AuthenticatedAppDocentesRouteImport } from './routes/_authenticated/app/docentes'
import { Route as AuthenticatedAppCursosRouteImport } from './routes/_authenticated/app/cursos'
import { Route as AuthenticatedAppCertificadosRouteImport } from './routes/_authenticated/app/certificados'
import { Route as AuthenticatedAppAlunosRouteImport } from './routes/_authenticated/app/alunos'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/app/',
  path: '/app/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppDocentesRoute =
  AuthenticatedAppDocentesRouteImport.update({
    id: '/app/docentes',
    path: '/app/docentes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppCursosRoute = AuthenticatedAppCursosRouteImport.update({
  id: '/app/cursos',
  path: '/app/cursos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppCertificadosRoute =
  AuthenticatedAppCertificadosRouteImport.update({
    id: '/app/certificados',
    path: '/app/certificados',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppAlunosRoute = AuthenticatedAppAlunosRouteImport.update({
  id: '/app/alunos',
  path: '/app/alunos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/app/alunos': typeof AuthenticatedAppAlunosRoute
  '/app/certificados': typeof AuthenticatedAppCertificadosRoute
  '/app/cursos': typeof AuthenticatedAppCursosRoute
  '/app/docentes': typeof AuthenticatedAppDocentesRoute
  '/app/': typeof AuthenticatedAppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/app/alunos': typeof AuthenticatedAppAlunosRoute
  '/app/certificados': typeof AuthenticatedAppCertificadosRoute
  '/app/cursos': typeof AuthenticatedAppCursosRoute
  '/app/docentes': typeof AuthenticatedAppDocentesRoute
  '/app': typeof AuthenticatedAppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/app/alunos': typeof AuthenticatedAppAlunosRoute
  '/_authenticated/app/certificados': typeof AuthenticatedAppCertificadosRoute
  '/_authenticated/app/cursos': typeof AuthenticatedAppCursosRoute
  '/_authenticated/app/docentes': typeof AuthenticatedAppDocentesRoute
  '/_authenticated/app/': typeof AuthenticatedAppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/app/alunos'
    | '/app/certificados'
    | '/app/cursos'
    | '/app/docentes'
    | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/app/alunos'
    | '/app/certificados'
    | '/app/cursos'
    | '/app/docentes'
    | '/app'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/app/alunos'
    | '/_authenticated/app/certificados'
    | '/_authenticated/app/cursos'
    | '/_authenticated/app/docentes'
    | '/_authenticated/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app/': {
      id: '/_authenticated/app/'
      path: '/app'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/docentes': {
      id: '/_authenticated/app/docentes'
      path: '/app/docentes'
      fullPath: '/app/docentes'
      preLoaderRoute: typeof AuthenticatedAppDocentesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/cursos': {
      id: '/_authenticated/app/cursos'
      path: '/app/cursos'
      fullPath: '/app/cursos'
      preLoaderRoute: typeof AuthenticatedAppCursosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/certificados': {
      id: '/_authenticated/app/certificados'
      path: '/app/certificados'
      fullPath: '/app/certificados'
      preLoaderRoute: typeof AuthenticatedAppCertificadosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/alunos': {
      id: '/_authenticated/app/alunos'
      path: '/app/alunos'
      fullPath: '/app/alunos'
      preLoaderRoute: typeof AuthenticatedAppAlunosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAppAlunosRoute: typeof AuthenticatedAppAlunosRoute
  AuthenticatedAppCertificadosRoute: typeof AuthenticatedAppCertificadosRoute
  AuthenticatedAppCursosRoute: typeof AuthenticatedAppCursosRoute
  AuthenticatedAppDocentesRoute: typeof AuthenticatedAppDocentesRoute
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAppAlunosRoute: AuthenticatedAppAlunosRoute,
  AuthenticatedAppCertificadosRoute: AuthenticatedAppCertificadosRoute,
  AuthenticatedAppCursosRoute: AuthenticatedAppCursosRoute,
  AuthenticatedAppDocentesRoute: AuthenticatedAppDocentesRoute,
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
