ALTER TABLE public.certificados_registros
  ALTER COLUMN cpf DROP NOT NULL,
  ALTER COLUMN curso DROP NOT NULL,
  ALTER COLUMN instituicao DROP NOT NULL,
  ALTER COLUMN estado DROP NOT NULL,
  ALTER COLUMN cidade DROP NOT NULL,
  ALTER COLUMN endereco DROP NOT NULL,
  ALTER COLUMN registro DROP NOT NULL,
  ALTER COLUMN data_nascimento DROP NOT NULL,
  ALTER COLUMN nome DROP NOT NULL;